### ISSUE TITLE
Petición: Añadir enlaces de navegación para facilitar lectura lineal en la web

### ISSUE THREAD

**Issue by jdevera** [sdelquin/aprendepython#1]
Aunque está disponible la versión en pdf, si uno quiere leer esto de principio a fin en la web, sería mucho más cómodo con enlaces de navegación que te lleven a la siguiente página al final del contenido.

**Comment by sdelquin** [comment]
Está sobre Sphinx. Tendría que investigar si eso se puede hacer...

**Comment by jdevera** [comment]
https://stackoverflow.com/a/28918624 :)

**Comment by jdevera** [comment]
Esto despliega automáticamente al hacer merge? No veo los cambios.

**Comment by sdelquin** [comment]
Sí pero tengo que arreglar una cosilla 👍🏻

**Comment by sdelquin** [comment]
Desplegado!
