### ISSUE TITLE
Recomendación: Poner la URLs en español

### ISSUE THREAD

**Issue by jdevera** [sdelquin/aprendepython#2]
Las URLs de la documentación de este contenido en español serían más consistentes si estuviera en español.

**Comment by sdelquin** [comment]
¿Te refieres a alguna sección en concreto? ¿O en general?

**Comment by jdevera** [comment]
Todas. A mí me parecen un poco como parte del contenido.

**Comment by sdelquin** [comment]
Como norma general intenté buscar URL en español pero habían algunas que no las encontraba y por eso las dejé en inglés. Pero es verdad que tengo que revisar e intentar dejarlas todas en español o al menos las máximas posibles. Gracias por la sugerencia￼
