### ISSUE TITLE
Ejercicio con descripción incorrecta

### ISSUE THREAD

**Issue by asterion** [sdelquin/aprendepython#27]
El ejercicio 1 de repaso de la [página de lista](https://github.com/sdelquin/aprendepython/blob/master/core/datastructures/lists.rst) indica buscar el valor máximo pero el código de ejemplo busca el valor mínimo al igual que las indicaciones de entrada y salida.

**Comment by sdelquin** [comment]
Muchas gracias @asterion. Estas cosas me vienen muy bien así voy puliendo los errores. Lo arreglo ya mismo.
