### ISSUE TITLE
Error de codificación en Latex

### ISSUE THREAD

**Issue by josecox13** [sdelquin/aprendepython#34]
Hola! Creo que en la sección 6.1.3, en la parte que se refiere a "Múltiples tipos" a la hora de definir funciones, no se está codificando bien la barra de separación | en la tabla de ejemplos válidos.
No hay prisa, sólo para que lo tengas en cuenta.

Una vez más, gracias por tu inmensa labor

**Comment by sdelquin** [comment]
Gracias! Creo que ya está solucionado.
